DROP TABLE IF EXISTS CONTACT;

CREATE TABLE STUDENTS (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  BIRTH_DATE DATE NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PHONE_NUMBER VARCHAR(20) NOT NULL,
  KNOWLEDGE VARCHAR(200) NULL,
  ENGLISH_LEVEL VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`));